version: '3'

services:

    # nginx
    nginx:
        image: nginx:latest
        container_name: nginx
        working_dir: /var/www
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    # php
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php
        working_dir: /var/www
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/
            - ~/.ssh:/root/.ssh
        environment:
            - APP_ENV=dev

networks:
    default:
        external:
            name: sdnet

volumes:
    mysql_data:
        driver: "local"